### ISSUE TITLE
Incorrect version number of .jar in runme.sh

### ISSUE THREAD

**Issue by oshibka404** [Rothamsted/ondex-knet-builder#18]
Link "[Latest stable release](http://ondex.rothamsted.ac.uk/nexus/content/groups/public/net/sourceforge/ondex/apps/ondex-mini/2.1/ondex-mini-2.1-packaged-distro.zip)" on the [Downloads](https://github.com/Rothamsted/ondex-knet-builder/wiki/Downloads) page leads to a `.zip`-file containing following string in `runme.sh`:
```sh
java -Dondex.dir="$MYDIR/data" -jar "$MYDIR/lib/ondex-mini-2.0.1-SNAPSHOT.jar" \
     -ubla -ptest -w$WORKFLOW $PLUGIN_ARGS
```
but there is no such a file in `lib`-folder. There is `ondex-mini-2.1.jar` only.

**Comment by marco-brandizi** [comment]
Hi @oshibka404, thanks for your interest in Ondex.

Sorry, we have to issue a new release in the incoming weeks. This problem was fixed a while ago and the snapshot releases have the correct version in the scripts, including [this case](https://github.com/Rothamsted/ondex-knet-builder/blob/master/ondex-mini/src/main/scripts/runme.sh). Please, for the time being, use the [dev/snapshot release](http://ondex.rothamsted.ac.uk/nexus/content/groups/public-snapshots/net/sourceforge/ondex/apps/ondex-mini/2.1.1-SNAPSHOT/ondex-mini-2.1.1-20190529.124232-136-packaged-distro.zip).
